In [1]:
import numpy as np

In [2]:
size = 3
m = np.arange(1, size*size+1, 1).reshape(size, size)
m[size-1,size-1] = 0
saida_esperada = m.copy()

In [3]:
#np.random.shuffle(m)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [4]:
def busca_zero(m):
    i= 0
    j= 0
    s = 1500
    aux =0
    while (i<size) and (m[i,j]!= 0):
        while (j<size) and (m[i,j]!= 0):
            j=j+1
        if j!=size and m[i,j]==0:
            break
        else:
            j=0
            i=i+1
        
    if i >= size:
        i = size-1
    if j >= size:
        j = size-1
        
            
    #Verifica se o 0 está nos cantos(0) ou nas bordas(1) ou no meio(2)
        
    if (i == 0):
        aux = 1
        if (j == 0) or (j == size-1):
            s = 0
        else:
            s = 1
    elif i == size-1:
        if (j == 0) or (j == size-1):
            s = 0
        else:
            s = 1
    elif (j == 0) or (j == size-1):
        s = 1
    else:
        s = 2           
        
    return i,j,s

In [5]:
from random import randint

def embaralha(m):
    i,j,s = busca_zero(m)
    #print(i, j, s)
    #print(m)
    
    if s == 0:
        rand = randint(0,1)
        if rand == 0:
            if j == 0:
                aux = m[i,j+1]
                m[i,j+1] = 0
                m[i,j] = aux
            else:
                aux = m[i, j-1]
                m[i, j-1] = 0
                m[i,j] = aux
        else:
            if i == 0:
                aux = m[i+1,j]
                m[i+1,j] = 0
                m[i,j] = aux
            else:
                aux = m[i-1, j]
                m[i-1, j] = 0
                m[i,j] = aux 
    elif s == 1:
        rand = randint(0,2)
        if rand == 0:
            if i == 0 or i == size-1:
                #borda superior ou inferior -> troca com o da direita
                aux = m[i,j+1]
                m[i,j+1] = 0
                m[i,j] = aux
            else:
                #borda lateral -> troca com o de baixo
                aux = m[i+1,j]
                m[i+1,j] = 0
                m[i,j] = aux
        elif rand == 1:
            if i == 0 or i == size-1:
                #borda superior ou inferior -> troca com o da esquerda
                aux = m[i, j-1]
                m[i, j-1] = 0
                m[i,j] = aux
            else:
                #borda lateral -> troca com o de cima
                #print(m)
                #print(i,j,s)
                aux = m[i-1, j]
                m[i-1, j] = 0
                m[i,j] = aux
        else:
            if i == 0:
                #borda superior -> troca com o de baixo
                aux = m[i+1,j]
                m[i+1,j] = 0
                m[i,j] = aux
            elif i == size-1:
                #borda inferior -> troca com o de cima
                aux = m[i-1, j]
                m[i-1, j] = 0
                m[i,j] = aux
            elif j == 0:
                #borda lateral esquerda -> troca com o do lado direito
                #print(m)
                #print(i,j,s)
                aux = m[i,j+1]
                m[i,j+1] = 0
                m[i,j] = aux
            else:
                #borda lateral direita -> troca com o do lado esquerdo
                aux = m[i, j-1]
                m[i, j-1] = 0
                m[i,j] = aux
    else:
        rand = randint(0,3)
        if rand == 0:
            aux = m[i,j+1]
            m[i,j+1] = 0
            m[i,j] = aux
        elif rand == 1:
            aux = m[i, j-1]
            m[i, j-1] = 0
            m[i,j] = aux
        elif rand == 2:
            aux = m[i+1,j]
            m[i+1,j] = 0
            m[i,j] = aux
        else:
            aux = m[i-1, j]
            m[i-1, j] = 0
            m[i,j] = aux
            
    return m

In [6]:
for x in range(0, 5):
    embaralha(m)
m

array([[1, 2, 3],
       [5, 7, 6],
       [4, 0, 8]])

In [7]:
class Node:
    def __init__(self, data):
        
        self.nodo_pai = None
        self.direita = None
        self.esquerda = None
        self.cima = None
        self.baixo = None
        self.data = data
        self.h = 0
        self.f = 0
        self.g = 0
        
    def insert(self, data):
        if self.direita is None:
            self.direita = Node(data)            
        elif self.esquerda is None:
            self.esquerda = Node(data)
        elif self.cima is None:
            self.cima = Node(data)
        elif self.baixo is None:
            self.baixo = Node(data)

In [8]:
def movimento(m):
    i,j,s = busca_zero(m.data)
    saidas = []
    cont = 0
    v = 0
    #print(i, j, s)
    #print(m_aux)
    
    if s == 0:   
        cont = 0
        v = 2
        for cont in range (0,2):            
            m_aux = m.data.copy()
            if cont == 0:
                if j == 0:
                    aux = m_aux[i,j+1]
                    m_aux[i,j+1] = 0
                    m_aux[i,j] = aux
                else:
                    aux = m_aux[i, j-1]
                    m_aux[i, j-1] = 0
                    m_aux[i,j] = aux
                #print("s = 0 cont = 0")
                #print(m_aux)
                #print(" ")
            else:
                if i == 0:
                    aux = m_aux[i+1,j]
                    m_aux[i+1,j] = 0
                    m_aux[i,j] = aux
                else:
                    aux = m_aux[i-1, j]
                    m_aux[i-1, j] = 0
                    m_aux[i,j] = aux
                #print("s = 0 cont = 1")
                #print(m_aux)
                #print(" ")
            m_aux = Node(m_aux)
            saidas.append(m_aux)
            m_aux = []            
            
    elif s == 1:
        
        cont = 0
        v = 3
        for cont in range (0,3):
            m_aux = m.data.copy()
            if cont == 0:
                if i == 0 or i == size-1:
                    #borda superior ou inferior -> troca com_aux o da direita
                    aux = m_aux[i,j+1]
                    m_aux[i,j+1] = 0
                    m_aux[i,j] = aux
                else:
                    #borda lateral -> troca com_aux o de baixo
                    aux = m_aux[i+1,j]
                    m_aux[i+1,j] = 0
                    m_aux[i,j] = aux
                #print("s = 1 cont = 0")
                #print(m_aux)
                #print(" ")
            elif cont == 1:
                if i == 0 or i == size-1:
                    #borda superior ou inferior -> troca com_aux o da esquerda
                    aux = m_aux[i, j-1]
                    m_aux[i, j-1] = 0
                    m_aux[i,j] = aux
                else:
                    #borda lateral -> troca com_aux o de cim_auxa
                    #print(m_aux)
                    #print(i,j,s)
                    aux = m_aux[i-1, j]
                    m_aux[i-1, j] = 0
                    m_aux[i,j] = aux
                #print("s = 1 cont = 1")
                #print(m_aux)
                #print(" ")
            else:
                if i == 0:
                    #borda superior -> troca com_aux o de baixo
                    aux = m_aux[i+1,j]
                    m_aux[i+1,j] = 0
                    m_aux[i,j] = aux
                elif i == size-1:
                    #borda inferior -> troca com_aux o de cim_auxa
                    aux = m_aux[i-1, j]
                    m_aux[i-1, j] = 0
                    m_aux[i,j] = aux
                elif j == 0:
                    #borda lateral esquerda -> troca com_aux o do lado direito
                    #print(m_aux)
                    #print(i,j,s)
                    aux = m_aux[i,j+1]
                    m_aux[i,j+1] = 0
                    m_aux[i,j] = aux
                else:
                    #borda lateral direita -> troca com_aux o do lado esquerdo
                    aux = m_aux[i, j-1]
                    m_aux[i, j-1] = 0
                    m_aux[i,j] = aux
                #print("s = 1 cont = 2")
                #print(m_aux)
                #print(" ")
            m_aux = Node(m_aux)
            saidas.append(m_aux)
            m_aux = []
    else:
        cont = 0
        v = 4
        for cont in range (0,4):
            m_aux = m.data.copy()
            if cont == 0:
                aux = m_aux[i,j+1]
                m_aux[i,j+1] = 0
                m_aux[i,j] = aux
                #print("s = 2 cont = 0")
                #print(m_aux)
                #print(" ")
            elif cont == 1:
                aux = m_aux[i, j-1]
                m_aux[i, j-1] = 0
                m_aux[i,j] = aux
                #print("s = 2 cont = 1")
                #print(m_aux)
                #print(" ")
            elif cont == 2:
                aux = m_aux[i+1,j]
                m_aux[i+1,j] = 0
                m_aux[i,j] = aux
                #print("s = 2 cont = 2")
                #print(m_aux)
                #print(" ")
            else:
                aux = m_aux[i-1, j]
                m_aux[i-1, j] = 0
                m_aux[i,j] = aux
                #print("s = 2 cont = 3")
                #print(m_aux)
                #print(" ")
            m_aux = Node(m_aux)
            saidas.append(m_aux)
            m_aux = []
            
    return saidas, v

In [9]:
def busca_valor(m, x):
    i= 0
    j= 0
    while (i<size) and (m[i,j]!= x):
        while (j<size) and (m[i,j]!= x):
            j=j+1
        if j!=size and m[i,j]==x:
            break
        else:
            j=0
            i=i+1
    return i,j

In [10]:
def heuristica(m):
    h = 0
    for i in range(0, size-1):
        for j in range(0, size-1):
            if m[i,j] != saida_esperada[i,j]:
                a, b = busca_valor(saida_esperada, m[i,j])
                h = abs(i-a) + abs(j-b)            
    return h

In [11]:
def prioridade(dado):
    return dado.f

solucao_encontrada = False
nos_abertos = 0

lista_dados = list()
lista_dados.append(Node(m))
matriz_embaralhada = m.copy()
nos_abertos = nos_abertos +1

def abre_no(raiz): 

    rs, v = movimento(raiz)
    for i in range (0,v):
        rs[i].nodo_pai = raiz
        rs[i].h = heuristica(rs[i].data)
        rs[i].g = raiz.f - raiz.h + 1
        rs[i].f = rs[i].g + rs[i].h
        raiz.insert(rs[i].data)        
    lista_dados.extend(rs)  
    lista_dados.sort(key = prioridade)

In [12]:
matriz = None
while lista_dados:
    matriz = lista_dados.pop(0)
    #print(matriz.h)
    nos_abertos = nos_abertos +1

    if not np.array_equal(matriz.data,saida_esperada):
        abre_no(matriz)
    else:
        solucao_encontrada = True
        break


if solucao_encontrada:
    #print(matriz.data)
    print("Nós abertos: " + str(nos_abertos))
    print(" ")
    caminho = list()
    count = 0
    
    while matriz != None:
        caminho.append(matriz.data)
        matriz = matriz.nodo_pai
        count = count +1
        
    caminho.reverse()
    #print(count)
    for i in range(0, count):
        print(caminho[i])
    #print(caminho)

Nós abertos: 48
 
[[1 2 3]
 [5 7 6]
 [4 0 8]]
[[1 2 3]
 [5 0 6]
 [4 7 8]]
[[1 2 3]
 [0 5 6]
 [4 7 8]]
[[1 2 3]
 [4 5 6]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
