In [1]:
import numpy as np

In [2]:
size = 3
m = np.arange(0, size*size, 1).reshape(size, size)

In [3]:
#np.random.shuffle(m)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
def busca_zero(m):
    i= 0
    j= 0
    s = 1500
    aux =0
    while (i<size) and (m[i,j]!= 0):
        while (j<size) and (m[i,j]!= 0):
            j=j+1
        if j!=3 and m[i,j]==0:
            break
        else:
            j=0
            i=i+1
        
    if i >= size:
        i = size-1
    if j >= size:
        j = size-1
        
            
    #Verifica se o 0 está nos cantos(0) ou nas bordas(1) ou no meio(2)
        
    if (i == 0):
        aux = 1
        if (j == 0) or (j == size-1):
            s = 0
        else:
            s = 1
    elif i == size-1:
        if (j == 0) or (j == size-1):
            s = 0
        else:
            s = 1
    elif (j == 0) or (j == size-1):
        s = 1
    else:
        s = 2           
        
    return i,j,s

In [5]:
print(busca_zero(m))

(0, 0, 0)


In [6]:
from random import randint

def embaralha(m):
    i,j,s = busca_zero(m)
    #print(i, j, s)
    #print(m)
    
    if s == 0:
        rand = randint(0,1)
        if rand == 0:
            if j == 0:
                aux = m[i,j+1]
                m[i,j+1] = 0
                m[i,j] = aux
            else:
                aux = m[i, j-1]
                m[i, j-1] = 0
                m[i,j] = aux
        else:
            if i == 0:
                aux = m[i+1,j]
                m[i+1,j] = 0
                m[i,j] = aux
            else:
                aux = m[i-1, j]
                m[i-1, j] = 0
                m[i,j] = aux 
    elif s == 1:
        rand = randint(0,2)
        if rand == 0:
            if i == 0 or i == size-1:
                #borda superior ou inferior -> troca com o da direita
                aux = m[i,j+1]
                m[i,j+1] = 0
                m[i,j] = aux
            else:
                #borda lateral -> troca com o de baixo
                aux = m[i+1,j]
                m[i+1,j] = 0
                m[i,j] = aux
        elif rand == 1:
            if i == 0 or i == size-1:
                #borda superior ou inferior -> troca com o da esquerda
                aux = m[i, j-1]
                m[i, j-1] = 0
                m[i,j] = aux
            else:
                #borda lateral -> troca com o de cima
                #print(m)
                #print(i,j,s)
                aux = m[i-1, j]
                m[i-1, j] = 0
                m[i,j] = aux
        else:
            if i == 0:
                #borda superior -> troca com o de baixo
                aux = m[i+1,j]
                m[i+1,j] = 0
                m[i,j] = aux
            elif i == size-1:
                #borda inferior -> troca com o de cima
                aux = m[i-1, j]
                m[i-1, j] = 0
                m[i,j] = aux
            elif j == 0:
                #borda lateral esquerda -> troca com o do lado direito
                #print(m)
                #print(i,j,s)
                aux = m[i,j+1]
                m[i,j+1] = 0
                m[i,j] = aux
            else:
                #borda lateral direita -> troca com o do lado esquerdo
                aux = m[i, j-1]
                m[i, j-1] = 0
                m[i,j] = aux
    else:
        rand = randint(0,3)
        if rand == 0:
            aux = m[i,j+1]
            m[i,j+1] = 0
            m[i,j] = aux
        elif rand == 1:
            aux = m[i, j-1]
            m[i, j-1] = 0
            m[i,j] = aux
        elif rand == 2:
            aux = m[i+1,j]
            m[i+1,j] = 0
            m[i,j] = aux
        else:
            aux = m[i-1, j]
            m[i-1, j] = 0
            m[i,j] = aux
            
    return m

In [7]:
for x in range(0, 2):
    embaralha(m)
m

array([[3, 1, 2],
       [4, 0, 5],
       [6, 7, 8]])

In [8]:
class Node:
    def __init__(self, data):
        
        self.nodo_pai = None
        self.direita = None
        self.esquerda = None
        self.cima = None
        self.baixo = None
        self.data = data
        
    def insert(self, data, nodo):
        if self.direita is None:
            self.direita = Node(data)            
        elif self.esquerda is None:
            self.esquerda = Node(data)
        elif self.cima is None:
            self.cima = Node(data)
        elif self.baixo is None:
            self.baixo = Node(data)
        self.nodo_pai = nodo

In [9]:
def movimento(m):
    i,j,s = busca_zero(m.data)
    saidas = []
    cont = 0
    v = 0
    #print(i, j, s)
    #print(m_aux)
    
    if s == 0:   
        cont = 0
        v = 2
        for cont in range (0,2):            
            m_aux = m.data.copy()
            if cont == 0:
                if j == 0:
                    aux = m_aux[i,j+1]
                    m_aux[i,j+1] = 0
                    m_aux[i,j] = aux
                else:
                    aux = m_aux[i, j-1]
                    m_aux[i, j-1] = 0
                    m_aux[i,j] = aux                
            else:
                if i == 0:
                    aux = m_aux[i+1,j]
                    m_aux[i+1,j] = 0
                    m_aux[i,j] = aux
                else:
                    aux = m_aux[i-1, j]
                    m_aux[i-1, j] = 0
                    m_aux[i,j] = aux
            m_aux = Node(m_aux)
            saidas.append(m_aux)
            m_aux = []            
            
    elif s == 1:
        
        cont = 0
        v = 3
        for cont in range (0,3):
            m_aux = m.data.copy()
            if cont == 0:
                if i == 0 or i == size-1:
                    #borda superior ou inferior -> troca com_aux o da direita
                    aux = m_aux[i,j+1]
                    m_aux[i,j+1] = 0
                    m_aux[i,j] = aux
                else:
                    #borda lateral -> troca com_aux o de baixo
                    aux = m_aux[i+1,j]
                    m_aux[i+1,j] = 0
                    m_aux[i,j] = aux
            elif cont == 1:
                if i == 0 or i == size-1:
                    #borda superior ou inferior -> troca com_aux o da esquerda
                    aux = m_aux[i, j-1]
                    m_aux[i, j-1] = 0
                    m_aux[i,j] = aux
                else:
                    #borda lateral -> troca com_aux o de cim_auxa
                    #print(m_aux)
                    #print(i,j,s)
                    aux = m_aux[i-1, j]
                    m_aux[i-1, j] = 0
                    m_aux[i,j] = aux
            else:
                if i == 0:
                    #borda superior -> troca com_aux o de baixo
                    aux = m_aux[i+1,j]
                    m_aux[i+1,j] = 0
                    m_aux[i,j] = aux
                elif i == size-1:
                    #borda inferior -> troca com_aux o de cim_auxa
                    aux = m_aux[i-1, j]
                    m_aux[i-1, j] = 0
                    m_aux[i,j] = aux
                elif j == 0:
                    #borda lateral esquerda -> troca com_aux o do lado direito
                    #print(m_aux)
                    #print(i,j,s)
                    aux = m_aux[i,j+1]
                    m_aux[i,j+1] = 0
                    m_aux[i,j] = aux
                else:
                    #borda lateral direita -> troca com_aux o do lado esquerdo
                    aux = m_aux[i, j-1]
                    m_aux[i, j-1] = 0
                    m_aux[i,j] = aux
            m_aux = Node(m_aux)
            saidas.append(m_aux)
            m_aux = []
    else:
        cont = 0
        v = 4
        for cont in range (0,4):
            m_aux = m.data.copy()
            if cont == 0:
                aux = m_aux[i,j+1]
                m_aux[i,j+1] = 0
                m_aux[i,j] = aux
            elif cont == 1:
                aux = m_aux[i, j-1]
                m_aux[i, j-1] = 0
                m_aux[i,j] = aux
            elif cont == 2:
                aux = m_aux[i+1,j]
                m_aux[i+1,j] = 0
                m_aux[i,j] = aux
            else:
                aux = m_aux[i-1, j]
                m_aux[i-1, j] = 0
                m_aux[i,j] = aux
            m_aux = Node(m_aux)
            saidas.append(m_aux)
            m_aux = []
            
    return saidas

In [10]:
saida_esperada = np.arange(1, size*size+1, 1).reshape(size, size)
saida_esperada[size-1,size-1] = 0
solucao_encontrada = False

lista_dados = list()
lista_dados.append(Node(m))

def abre_no(m): 

    raiz = Node(m)
    rs = movimento(raiz)
    lista_dados.extend(rs) 

In [11]:
while lista_dados:
    matriz = lista_dados.pop(0)
    print(matriz.data)
    print(saida_esperada)
    print(" ")

    if not np.array_equal(matriz.data,saida_esperada):
        abre_no(matriz.data)
    else:
        solucao_encontrada = True
        break

if solucao_encontrada:
    print(matriz.data)

[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 8]
 [6 7 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 0]
 [4 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [0 6 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 2 0]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 3 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5

[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[1 0 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 0]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 7 5]
 [4 6 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5

[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [0 6 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 2 0]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 3 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [7 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 0 5]
 [7 4 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [7 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 0]
 [6 4 2]
 [7 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 0 4]
 [7 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [7 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 0 5]
 [7 4 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5

 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [0 6 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 0]
 [4 7 2]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 7]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 0]
 [4 7 2]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 3 1]
 [4 7 2]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 7 1]
 [4 0 2]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 0]
 [4 7 2]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 7]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 8 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 0]
 [4 7 2]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 7]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 7]
 [0 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 1 2]
 [3

 
[[4 3 2]
 [6 1 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [6 0 5]
 [7 1 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [6 1 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 3 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 2 0]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 3 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [6 1 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 3 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 5 8]
 [6 7 0]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 0]
 [1 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [6 1 5]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[0 3 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 0 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1

[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 1]
 [4 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 1]
 [4 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 1]
 [0 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 5 1]
 [4 2 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 5 1]
 [0 4 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 5 1]
 [4 7 2]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 1]
 [4 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 1]
 [6 5 2]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 1]
 [0 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 1]
 [4 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 1]
 [0 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5

 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [6 1 5]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [0 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [0 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [0 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 0 2]
 [1 3 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 8]
 [6 0 7]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 1]
 [4 5 2]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[

 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [6 4 5]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[1 0 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 0]
 [6 8 5]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 7 5]
 [4 6 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[

 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 2 5]
 [4 1 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 2 5]
 [0 4 1]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 2 5]
 [4 7 1]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 5]
 [4 2 1]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 2 5]
 [4 1 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [0 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 5 0]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [0 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 1 2]
 [4 7 5]
 [6 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [6 1 5]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [0 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[3 0 2]
 [4 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [0 1 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 
[[4 3 2]
 [1 5 0]
 [6 7 8]]
[[1 

KeyboardInterrupt: 